allowBuilds:
  unrs-resolver: true
overrides:
  '@babel/core@<=7.29.0': '>=7.29.6'
  brace-expansion@<1.1.13: '>=1.1.13'
  brace-expansion@>=2.0.0 <2.0.3: '>=2.0.3'
  fast-xml-builder@<=1.1.6: '>=1.1.7'
  fast-xml-parser@<5.7.0: '>=5.7.0'
  handlebars@>=4.0.0 <4.7.9: '>=4.7.9'
  handlebars@>=4.0.0 <=4.7.8: '>=4.7.9'
  handlebars@>=4.6.0 <=4.7.8: '>=4.7.9'
  js-yaml@<=4.1.1: '>=4.2.0'
  undici@<6.23.0: '>=6.23.0'
  undici@<6.24.0: '>=6.24.0'
  undici@>=6.0.0 <6.24.0: '>=6.24.0'
  undici@>=7.0.0 <7.28.0: '>=7.28.0'
  undici@>=7.23.0 <7.28.0: '>=7.28.0'
